version: '2'
services:
    phonebook-app:
        image: phonebook
        external_links:
            - phonebook-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/phonebook
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    phonebook-postgresql:
        extends:
            file: postgresql.yml
            service: phonebook-postgresql
